Task/dat 1226 use signed int
cyface-de/protos pull request #22
Opened 2022-06-02 09:50 UTC by hb0

2022-06-02 09:57 UTC, hb0 reviewed
pre-reviewed.

2022-06-02 09:57 UTC, hb0 commented on src/main/proto/de/cyface/protos/model/measurement.proto
> -   * Negative numbers are supported but encoded inefficiently in `uint` this data type, compared to `sint`.
I removed or updated those wrong statements that `uint` support negative numbers.

2022-06-02 09:57 UTC, hb0 commented on src/main/proto/de/cyface/protos/model/measurement.proto
> +  repeated sint64 timestamp = 1;
That's the relevant fix (1 of 4).

2022-06-02 09:57 UTC, hb0 commented on src/main/proto/de/cyface/protos/model/measurement.proto
> +  repeated sint64 timestamp = 1;
That's the relevant fix (2 of 4).

2022-06-02 09:57 UTC, hb0 commented on src/main/proto/de/cyface/protos/model/measurement.proto
> +  repeated sint64 timestamp = 1;
That's the relevant fix (4 of 4).

2022-06-02 09:57 UTC, hb0 commented on src/main/proto/de/cyface/protos/model/measurement.proto
>    uint64 timestamp = 1;
For non-`repeated` messages like `Events` we store only absolute `timestamp`s, i.e. we don't support negative numbers like in the `repeated` messages like `LocationRecords` and `Accelerations` where we store timestamp offsets and, thus, have to support negative numbers, too.

2022-06-02 09:57 UTC, hb0 commented on src/main/proto/de/cyface/protos/model/measurement.proto
>    uint64 timestamp = 16;
same as in `Events`  --> non `releated` --> we only store `absolute` timestamps.

2022-06-03 06:47 UTC, muthenberg requested changes
It would be cleaner to separate version changes and data type update into to PRs. If this is much of a hassle leave it, as it is now. But maybe remember for the future.

2022-06-03 06:47 UTC, muthenberg commented on README.adoc
>  Proprietary and confidential
The Repo is public, so this is wrong.

2022-06-06 07:19 UTC, merged